language: java
jdk: oraclejdk8
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m"
    - secure: "KpzAMqnf5+K5PNmZbcoiaSjWS//sVkPlbjrpb662rrkQcZHslqnAVmy2h+OsSaA6pefhRpzrSmys9vu7Ou4ZPNOBgxlmePOUl+MfEXOe+9EO3G6GLooyvzzk/9rsOYuHMiM6hrJZsPWF2NyIibElqE/l6YKuTUH9XOWnVbGZ+oY="
    

sudo: false
before_script:
- gem install jekyll --version '= 1.5.1'
- gem install RedCloth

script:
# Build documentation web site
- cd documentation
- ls
- jekyll build
- ls
- cd ../
# Integrate the documentation to Eclipse
- rm -rf plugins/org.obeonetwork.dsl.uml2.design.doc/html
- cp -r documentation/_site plugins/org.obeonetwork.dsl.uml2.design.doc/html
- ls plugins/org.obeonetwork.dsl.uml2.design.doc/html
# Build uml designer
- mvn clean verify
# Build uml designer products
- mvn clean verify -f releng/org.obeonetwork.dsl.uml2.product.parent/pom.xml
# Prepare local dirs to deploy: copy repository, bundles and tp
- chmod a+x prepare-deploy-local-dir.sh
- echo "$TRAVIS_TAG"
# Prepare tag dir if it is a tagged build
- if [[ "$TRAVIS_TAG" != "" ]]; then ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/$TRAVIS_TAG; fi
# Rename the zipped update site to nightly
- mv packaging/org.obeonetwork.dsl.uml2.update/target/org.obeonetwork.dsl.uml2.update-*-SNAPSHOT.zip packaging/org.obeonetwork.dsl.uml2.update/target/org.obeonetwork.dsl.uml2.update-nightly.zip
# Prepare the nightly dir
- ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/nightly

after_script:
# Promote web site on gh-pages only for master branch
- chmod a+x travis-promote.sh
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./travis-promote.sh; fi

deploy:
# Deploy nightly on s3
  - provider: s3
    access_key_id: AKIAJJVZATSVUD3VGHXA
    secret_access_key:
     secure: JR+FhCfNYeOp1kg6VsNFxDpXeI0MB27DZyzZ31krTrYhogtn5lPQZoRVc1e7/C/jaZqsbY3RZvjXnZOzTVxOgOV2VqbWGUzTwsnzLATiqtIvlq6MJvwDfaB/zRzYs3aVjss7QiVVsCsYh6rlihD4C3Xn2lRZIRMarTUYbVNYWyk=
    bucket: obeo-umldesigner-nightly
    local-dir: "${TRAVIS_BUILD_DIR}/nightly"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: "${TRAVIS_BRANCH}"
    on:
      branch: master 
  - provider: s3
    access_key_id: AKIAJJVZATSVUD3VGHXA
    secret_access_key:
     secure: JR+FhCfNYeOp1kg6VsNFxDpXeI0MB27DZyzZ31krTrYhogtn5lPQZoRVc1e7/C/jaZqsbY3RZvjXnZOzTVxOgOV2VqbWGUzTwsnzLATiqtIvlq6MJvwDfaB/zRzYs3aVjss7QiVVsCsYh6rlihD4C3Xn2lRZIRMarTUYbVNYWyk=
    bucket: obeo-umldesigner-nightly
    local-dir: "${TRAVIS_BUILD_DIR}/nightly"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: "${TRAVIS_BRANCH}"
    on:
      branch: 5.0.x  
  - provider: s3
    access_key_id: AKIAJJVZATSVUD3VGHXA
    secret_access_key:
     secure: JR+FhCfNYeOp1kg6VsNFxDpXeI0MB27DZyzZ31krTrYhogtn5lPQZoRVc1e7/C/jaZqsbY3RZvjXnZOzTVxOgOV2VqbWGUzTwsnzLATiqtIvlq6MJvwDfaB/zRzYs3aVjss7QiVVsCsYh6rlihD4C3Xn2lRZIRMarTUYbVNYWyk=
    bucket: obeo-umldesigner-nightly
    local-dir: "${TRAVIS_BUILD_DIR}/nightly"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: "${TRAVIS_BRANCH}"
    on:
      branch: 5.0.x_juno_3.8
# Deploy release on s3
  - provider: s3
    access_key_id: AKIAJJVZATSVUD3VGHXA
    secret_access_key:
     secure: JR+FhCfNYeOp1kg6VsNFxDpXeI0MB27DZyzZ31krTrYhogtn5lPQZoRVc1e7/C/jaZqsbY3RZvjXnZOzTVxOgOV2VqbWGUzTwsnzLATiqtIvlq6MJvwDfaB/zRzYs3aVjss7QiVVsCsYh6rlihD4C3Xn2lRZIRMarTUYbVNYWyk=
    bucket: obeo-umldesigner-releases
    local-dir: "${TRAVIS_BUILD_DIR}/${TRAVIS_TAG}"
    acl: public_read
    skip_cleanup: true
    region: eu-west-1
    upload-dir: "${TRAVIS_TAG}"
    on:
      tags: true
      all_branches: true
      repo: ObeoNetwork/UML-Designer
dd:
  secure: SVW8lL8L5J7f/AgTRm69vYlOVx+U/grtQM52Ue/ZaHtNhZEuXbz2FmPhMzK3k7Adlqw2vbrzmBe78svbHvMLOuqWGPfcmYlBLeSDQPp8VI6KLpGt+y2UltoSdLKjnXyn6KCerXYm4FTdqxtZDuso52THGNC0Enn3kHv6d9tR4qw=
